
filebeat.inputs:
  - type: log
    paths:
      - /mnt/log/*.log
  - type: docker
    containers:
      ids: '*'
      path: /usr/share/filebeat/dockerlogs
      stream: stderr

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "https"
  username: elastic
  # Read PW from filebeat.keystore
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]

setup.kibana:
  host: "http://kibana:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  protocol: "http"
  ssl.enabled: false
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]

xpack.monitoring.enabled: true

filebeat.modules:
- module: system
